services:
  web:
    build: ./mainWebService
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache
      - app
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server"]
    volumes:
      - redisdata:/data
  app:
    build: ./app
    ports:
      - "4000:4000"
volumes:
  pgdata:
  redisdata: